### PR TITLE
Python 3 compatibility fix

### PR DESCRIPTION
**Pull request by rpatterson**

### CODE REVIEW

**Comment by brandonwbrown** [comment]
i'd love if this was accepted. does this fix the 

'PdbMiddleware' object is not callable

issue?

**Comment by tomchristie** [comment]
I'd be up for handing over maintainership of the project if someone else wants to take care of new releases.

**Comment by rpatterson** [comment]
Not it!  ;-)  While I'm happy to contribute, I don't have the bandwidth to
be a maintainer.

**Comment by auvipy** [comment]
@tomchristie feel free to consider me as a maintainer of this project

**Comment by HassenPy** [comment]
@rpatterson, perfect, thanks!

**Pull request merged**
