### PR TITLE
Issue #41: Fix MIDDLEWARE_CLASSES error with `runserver`

### PR DESCRIPTION
**Pull request by gh640**
This is a small PR to address #41.

I read the contributing guide ( https://github.com/HassenPy/django-pdb/blob/master/CONTRIBUTING.md )but I couldn't judge if I may send PR or not in this case. I'm sorry if I disturb you with this PR.

After applying this change, I could use this package with Django 2.0.2.

Also, (in #40 ) I found you are planning to rewrite whole code. If you don't take PR for now to rewrite the project, please don't hesitate to reject this.

> Also, I'm planning to rewrite the whole project,

Thank you in advance.

### CODE REVIEW

**Comment by HassenPy** [comment]
Welcome @gh640 and thanks, i already started refactoring the project, not sure when i ll finish thou, i inherited the contribution guide and changed it locally, i ll try to update the project asup.

One thing you can do to get this merged is add a compatibility check, if the django version is >=1.10 use `MIDDLEWARE` instead of `MIDDLEWARE_CLASSES`.

**Comment by HassenPy** [comment]
actually that is the correct way to do it, i got this wrong.

**Comment by HassenPy** [comment]
probably failing to reproduce since the pdb/ipdb arguments are not being picked.

**Comment by HassenPy** [comment]
if anyone is in urgent need for this you can install @gh640's version with:  
``pip install git+https://github.com/gh640/django-pdb`

**Comment by gh640** [comment]
@HassenPy thank you for you response and taking the time to review the PR.

Actually I tested the function with `pdb GET parameter` which is different from the case you tested. As with the issue of option `--pdb` and `--ipdb` you told, I'll try investigating them.

Anyway, thank you for all of your work!

**Comment by gh640** [comment]
@HassenPy thank you for processing this!

I tested the option `--pdb` and `--ipdb` in my environment and it seems to work well... If I find any issue using this package, I'll let you know. Thank you for your swift and kind reaction :)

**Pull request merged**
